"""Offscreen render helper — Phase 4L screenshot pipeline.

Every `capture_*.py` script renders a real widget tree with Qt's
`offscreen` platform plugin (no display needed) and saves a
deterministic PNG. Same widgets in → same pixels out, so the docs
images can be regenerated by anyone, on CI, without a desktop.
"""

from __future__ import annotations

import os
import sys
from pathlib import Path

# Must be set before QApplication is constructed.
os.environ.setdefault("QT_QPA_PLATFORM", "offscreen")

# Repo root — capture/ is infra/scripts/capture/, so three parents up.
ROOT = Path(__file__).resolve().parents[3]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from PyQt6.QtCore import Qt  # noqa: E402
from PyQt6.QtGui import (  # noqa: E402
    QColor,
    QFont,
    QFontDatabase,
    QPainter,
)
from PyQt6.QtWidgets import QApplication, QWidget  # noqa: E402

# The `offscreen` QPA plugin ships with an empty font database — text
# would render as tofu boxes. We load a real sans-serif from the host
# OS and make it the application font so captures show actual glyphs.
_FONT_CANDIDATES = [
    r"C:\Windows\Fonts\segoeui.ttf",
    r"C:\Windows\Fonts\arial.ttf",
    "/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf",
    "/usr/share/fonts/truetype/liberation/LiberationSans-Regular.ttf",
    "/System/Library/Fonts/Supplemental/Arial.ttf",
]

# Where doc images land.
ASSETS = ROOT / "assets" / "screenshots"

_app: QApplication | None = None


def app() -> QApplication:
    """One shared offscreen QApplication for the whole capture run."""
    global _app
    if _app is None:
        _app = QApplication.instance() or QApplication(sys.argv)
    return _app


def _install_font() -> str:
    """Load a host sans-serif into the empty offscreen font database
    and make it the application default. Returns the family name."""
    for path in _FONT_CANDIDATES:
        if not Path(path).exists():
            continue
        fid = QFontDatabase.addApplicationFont(path)
        fams = QFontDatabase.applicationFontFamilies(fid)
        if fams:
            QApplication.setFont(QFont(fams[0], 10))
            return fams[0]
    return QApplication.font().family()


# Construct the QApplication at import time. Qt aborts the process if
# any QWidget is built before a QApplication exists — and capture
# scripts build their widget trees before calling `render()`.
app()
FONT_FAMILY = _install_font()


class Panel(QWidget):
    """A launcher-coloured rounded surface to mount cards onto, so a
    captured card reads against the real background it ships on."""

    def __init__(self, bg: str = "#13151b", radius: int = 14) -> None:
        super().__init__()
        self._bg = QColor(bg)
        self._radius = radius

    def paintEvent(self, _event) -> None:  # type: ignore[override]
        p = QPainter(self)
        p.setRenderHint(QPainter.RenderHint.Antialiasing)
        p.setPen(Qt.PenStyle.NoPen)
        p.setBrush(self._bg)
        p.drawRoundedRect(
            0, 0, self.width(), self.height(), self._radius, self._radius
        )
        p.end()


def render(widget: QWidget, name: str, *, scale: int = 2) -> Path:
    """Lay `widget` out, grab it to a PNG at `scale`×, return the path."""
    ASSETS.mkdir(parents=True, exist_ok=True)
    widget.setAttribute(Qt.WidgetAttribute.WA_DontShowOnScreen, True)
    widget.show()
    app().processEvents()
    widget.adjustSize()
    app().processEvents()

    pm = widget.grab()
    if scale != 1:
        pm = pm.scaled(
            pm.width() * scale,
            pm.height() * scale,
            Qt.AspectRatioMode.IgnoreAspectRatio,
            Qt.TransformationMode.SmoothTransformation,
        )
    out = ASSETS / f"{name}.png"
    pm.save(str(out))
    widget.hide()
    return out
